# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: concertapp_development
  pool: 5
  username: root
  password: mysql

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: concertapp_test
  pool: 5
  username: root
  password: mysql

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: concertapp_production
  pool: 5
  username: root
  password: mysql

